### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [dino217/firehose-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by dino217** [comment]
Oh I get it. Mobile devices assume that a website is made for desktops unless you include the <meta name="viewport"> tag that tells the mobile device that the page is mobile capable. I had tested for mobile before by merely narrowing my browser, but that isn't how a mobile browser works. I think I have fixed it now, but I don't have a mobile device with which to check it. I'll borrow one tomorrow, and close the issue once I'm sure.

**Comment by kenmazaika** [comment]
Exactly.  I just looked at your code and the line of code you added should do it.  Thumbs up. :+1:
